[package]
name = "balatro-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
mlua = { version = "0.11.6", features = ["luajit", "vendored"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.10.0"
strum = { version = "0.28.0", features = ["strum_macros", "derive"] }
